### ISSUE TITLE
how could I can  run this program in VScode? 

### ISSUE THREAD

**Issue by freeformgrit** [dylanmsu/caustic_engineering#1]
My error are as bellow:

cmd /c chcp 65001>nul && C:\TDM-GCC-64\bin\gcc.exe -fdiagnostics-color=always -g F:\nonimaing\caustic_engineering\main.cpp -o F:\nonimaing\caustic_engineering\main.exe
In file included from F:\nonimaing\caustic_engineering\main.cpp:15:
F:\nonimaing\caustic_engineering\CImg.h:475:10: fatal error: png.h: No such file or directory
  475 | #include "png.h"
  I already put the zilb and lpng in my current folder :caustic_engineering. but it is still wrong ? I am a novice in CPP. install packages seems diffcult to me. I am more than grateful if you could answer me. I am very interested in this caustic design, this solver you adopted will be fast!
  looking forward to your reply!

**Comment by dylanmsu** [comment]
That is because you will need to install [libpng](https://github.com/pnggroup/libpng) after installing [zlib](https://github.com/madler/zlib).

Zlib:
1. First download the zlib repo
2. Cd into it
3. Mkdir build_zlib
4. Cd build_zlib
5. Cmake -G "MinGW Makefiles" ..
6. Make
7. In an admin terminal run make install
8. Add "C:\Program Files (x86)\zlib\bin" to your path env variable.

Libpng:
1. Now do the same with the libpng repo
2. If it the cmake step sais it cant find zlib then you should try to reboot or there is something wrong with the installation of zlib
3. Add "C:\Program Files (x86)\libpng\lib", "C:\Program Files (x86)\libpng\bin", and "C:\Program Files (x86)\libpng\include" to your path env variable.

If everything went well, you should be able to build the program now!

If you still cant find png.h try to add include_directories(${PNG_INCLUDE_DIRS}) after find_package(PNG REQUIRED) in CMakeLists.txt

**Comment by dylanmsu** [comment]
If you want a gui, i made a very crude electron app that implements this code in the backend. https://github.com/dylanmsu/Caustic_Designer/releases/tag/release_V1_0_1

This is a simple installer and alot easier to setup

**Comment by freeformgrit** [comment]
very clear ! thank you very much !

**Comment by freeformgrit** [comment]
sorry to bother.There is an error:find_package(X11 CONFIG REQUIRED).Can‘t install this project in windows.This package depends on unix.

**Comment by dylanmsu** [comment]
My apologies. I accidentally kept these dependencies in the cmake file. Remove line 27 and 39 from CMakeLists.txt file, delete the contents of the build directory and try again.

**Comment by freeformgrit** [comment]
I am sorry for bothering you.I have some problems, after compiling your program, when I enter the parameters, I use your sample image and the program works fine.But after changing to my own image the program doesn't work, it doesn't respond.After changing to jpg format, it always reports an error.below
Does the image format have to be png?Are there any other requirements for png images?I've processed some images with matlab,and turn them into PNG format, and they are all gray.just as the dog below. but I can't read them use this program.Hoping for your reply!
![PixPin_2024-10-18_16-56-52](https://github.com/user-attachments/assets/c65c2f7a-dd58-4df3-aea5-676edb47f74f)
![dog1](https://github.com/user-attachments/assets/265d530a-452b-4407-bbc5-abd9e3abf127)

**Comment by freeformgrit** [comment]
the picture must be RGB format?like imageA = [m,n,o];NOT imageA = [M,N]? double or unit8?

**Comment by dylanmsu** [comment]
Hmm i don't know what is going wrong. Are you sure that the png images are properly encoded as png?

**Comment by freeformgrit** [comment]
> Hmm i don't know what is going wrong. Are you sure that the png images are properly encoded as png?
Yes, I'm sure, my intention was mainly to add a background gray scale to change the intensity between [0,1] to [0.2 1]; 
like this:
img = imread("logof1.jpg");
img_gray =  rgb2gray(img);


target_img =imadjust(img_gray);

J = imadjust(target_img,[0 1],[0.2 1]);
this is not a HIGH contrast but ensures that the algorithm can converge, what I didn't expect was ，I got into trouble...The image is indeed in png format...Obviously, it could be related to the following code, I'll try to figure out how to fix it...thank you anyway!
#include "CImg.h"

void image_to_grid(const cimg_library::CImg<unsigned char>& image, std::vector<std::vector<double>>& image_grid) {
    for (int i = 0; i < image.height(); ++i) {
        std::vector<double> row;
        for (int j = 0; j < image.width(); ++j) {
            double r = image(j, i, 0) / 255.0; // Normalize R component
            double g = image(j, i, 1) / 255.0; // Normalize G component
            double b = image(j, i, 2) / 255.0; // Normalize B component
            double gray = (0.299 * r) + (0.587 * g) + (0.114 * b); // Calculate grayscale value using luminosity method
            row.push_back(gray);
        }
        image_grid.push_back(row);
    }
}

**Comment by dylanmsu** [comment]
Can you provide the png image that doesn't work? Also adding a gray valve to the background won't work because the code maps all the pixels such that they are between 1.0 and 0.0 see line 335 in caustic_design.cpp. to play with the contrast you can adjust the convergence criteria in main.cpp on line 151. Increasing this value will lower the contract and speed up the calculation.

**Comment by freeformgrit** [comment]
Thank for your instrcution! This was very useful in solving my problem!I will modify the code and give you feedback later!Thanks!In the meantime I've put up a picture of my test, so you can test it and see if you have any problems.
[Uploading img.zip…]()

**Comment by freeformgrit** [comment]
plus ,buy the way,the version of LEAST SQUARE SOLVER can also run in windows?

**Comment by dylanmsu** [comment]
In theory it will be possible to run it on windows, but you have to manage to install ceres solver on windows. I haven't bothered it myself but there are some online tutorials for it.

**Comment by freeformgrit** [comment]
Problem solved, looks like it was because of me, the image probably did not need to be processed as grayscale.Just need to change the code as you said, I changed the code maps all pixels so that they are between 1.0 and 0.1, line 335 in caustic_design.cpp.Looks like they work well now! Thanks for your share!
