### ISSUE TITLE
Differences between this repo and Caustic-Design

### ISSUE THREAD

**Issue by Graysonnwu** [dylanmsu/caustic_engineering#2]
Hi!

I've noticed in the README file you mentioned this repo is based on the paper [Poisson-Based Continuous Surface Generation for Goal-Based Caustics](http://nishitalab.org/user/egaku/tog14/continuous_caustics.pdf) (Yue, 2014), while the Caustic-Design repo is based on the paper [High-contrast Computational Caustic Design](https://theialab.ca/pubs/schwartzburg2014caustics.pdf) (Schwartzburg, 2014)

I wonder are there any differences between them in terms of the final output quality?
It seems Schwartzburg's paper performs better with high-contrast images compared to Yue's. Is that true?

Much appreciated!

**Comment by dylanmsu** [comment]
Hi, yes that is correct. Schwartzburg's paper also handles singularities (thin points and lines) but the down side is that Schwartzburg's methods are slow and not patent free, while yue's paper is patent free. The downside to yue's paper is its low contrast. This means that not all the light that enters the lens is used to create the image and some light leaks to the black areas because of the incomplete transport mapping.

**Comment by Graysonnwu** [comment]
Ah, I see, so it's about patent.

I do hope you can continue working on that project though, things like non-square shapes, or running in terminal with no UI, are quite useful.

(ps. I saw you mentioned [in this issue](https://github.com/dylanmsu/Caustic-Design/issues/6#issuecomment-2217157983) that you will "first working on point light sources". Based on my manufacturing experience, that's not really necessary. Things work just fine with a point light source at the right distance, it's just the image is a bit larger. No distortion or whatever.

Like this: (image ----4m---- lens ----30cm---- torch)

![1728556403612](https://github.com/user-attachments/assets/4fbf0a53-d566-496e-8bab-ffe01775e393)


Thanks again for your reply!

**Comment by dylanmsu** [comment]
Hi, the yue et al implementation is fully terminal based and uses the aspect ratio of the provided image. A rectangular image results in a rectangular lens. 
And for the point light sources, it is useful to have exact control over the resulting caustic image even with point light sources. For example i want the image to be exactly a certain size with a licht source at a certain position. Also by using a point light source we have to account for the refraction on entering the lens. This is already implemented. You just have to edit a variable in the fresnel mapping and recompile.

**Comment by dylanmsu** [comment]
Also if i may ask, your fabricated results look really good! What cnc setup are you using?

**Comment by Graysonnwu** [comment]
> the yue et al implementation is fully terminal based and uses the aspect ratio of the provided image. A rectangular image results in a rectangular lens.

Yeah, I'm aware of that. I just want better quality though, so some inconvenience wouldn't matter.

> What cnc setup are you using?

Well actually, I asked a friend of mine to do the fabrication. He told me the set up is: (hopefully I didn't translate it wrong)

> This is highly dependent on the machine. For example, the spindle's vibration acceleration varies at different speeds, and every machine is different. The speed I use is 22k RPM. The spacing between two paths is 0.04 mm, with a G1 feed rate of F1000 and a stock allowance of 0.1 mm. The tool used is a 1.5 mm diameter ball-end mill.

I don't know some of the technical terms so I'll post his original text below:

> 这个和机器有很大关系，比如主轴在不同转速时震动加速度是不一样的，每台机器都不一样，我用的速度是22k/rpm.出平行距离0.04 ，g1速度f1000,预留量0.1。刀具是直径1.5mm球头刀

And his machine:

![1728564467096](https://github.com/user-attachments/assets/b9a5a91d-b889-4814-b0b7-c410ea5001c5)

And some product we made for Veritasium:

https://github.com/user-attachments/assets/a5df2236-52eb-4ba9-9558-47850b990729

**Comment by freeformgrit** [comment]
Dear dylanmsu: I noticed that you said "Even if we use a point light source, we need to consider the refraction of the light source as it enters the lens. This is already implemented. You just edit a variable in the Fresnel mapping and recompile", point source project in which project? [By the way, you are one of the best coders out there!You are right when you say that Schwartzburg's paper also handles singularities (fine dots and fine lines). yue's paper can't handle singularities, but we can take the input image and add a trace amount of grayscale background to it.That way the input is convex, so that's probably why the output simulation of the lena image is better than hello world.I suspect it might have something to do with the algorithm you used, otsolver, which requires the input to be a convex function.That's my opinion and some ideas for improving this project.

**Comment by freeformgrit** [comment]
I noticed that you are using a least squares algorithm to solve this problem, recommend an article's algorithm, **A Fast Algorithm for Optimal Transportation**, this FFT-OT algorithm is also very fast to compute and the code is open source.You can find the source code here-https://[www3.cs.stonybrook.edu](https://www3.cs.stonybrook.edu/~gu/)/~gu/.I uploaded the code,hope you can see these!maybe it can help for your project!
[FFT_OT.zip](https://github.com/user-attachments/files/17378812/FFT_OT.zip)

**Comment by dylanmsu** [comment]
@freeformgrit i see that the code for point light sources which accounts for input refraction is not pushed. My apologies. 

And for the contrast of yue's paper, if you dont check for triangle collapses and let the mesh fully deform you get an optimal mapping (identical to the results of otsolver, only alot slower). But my implementation of the poisson solver for the normal integration (hight mapping) breaks when the contrast is too high.  For example the hello world image. That's why I'm implementing a least squares solver for the normal mapping (see branches).

I have a branch of otsolver that has a program which takes vertices from the Target_Surface program and outputs the transported target points that you can use as light origin points to create a caustic lens in the Target_Surface program. This supports high contrast images and is still patent free as far as i know. And it's really fast.

I will look into FFT_OT how compatible this is for caustic design, looks interesting!

**Comment by Amritpal-Nijjar** [comment]
@dylanmsu I am curious about the Caustic-Design repo that seems to now be missing, would it be possible for me to get access to that repo or the code ? It would be greatly appreciated, thanks!

**Comment by dylanmsu** [comment]
You can still use the fork from Graysonnwu: https://github.com/Graysonnwu/Caustic-Design

**Comment by DouglasKooChenSoon** [comment]
@dylanmsu @Graysonnwu @Amritpal-Nijjar @freeformgrit    You guys are very awesome!!    I wanted to make myself caustics acrylics but i couldn't suceed in coding it.         I will share with you all my fabrication result ( i made my own CNC routing machine, might not be precise)    

Just to confirm with you all,    i will try out both methods:
Currently the @dylanmsu 's repo is based on "Poisson-Based Continuous Surface Generation for Goal-Based
Caustics" by Yue et al ?

And @Graysonnwu 's repo (Graysonnwu: https://github.com/Graysonnwu/Caustic-Design)  is based on "High-contrast Computational Caustic Design" by Yuliy Schwartzburg  et al ?

I am so excited to try these out!!

**Comment by Graysonnwu** [comment]
> And [@Graysonnwu](https://github.com/Graysonnwu) 's repo (Graysonnwu: https://github.com/Graysonnwu/Caustic-Design) is based on "High-contrast Computational Caustic Design" by Yuliy Schwartzburg et al ?

I will not steal credit from dylanmsu, he contributed a lot in that repo. But yes it is based on Schwartzburg's paper.
